// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNQ8hosOkeC2sd_lxo4ex53X0Wq2sOAG0',
    appId: '1:367892405378:web:f74a337d7c23c73f0ca89b',
    messagingSenderId: '367892405378',
    projectId: 'digital-campus-d2f80',
    authDomain: 'digital-campus-d2f80.firebaseapp.com',
    storageBucket: 'digital-campus-d2f80.firebasestorage.app',
    measurementId: 'G-0TGW42J8PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmUxknam1uxTNAcvZ_scnyL2OFRznXBjY',
    appId: '1:367892405378:android:71c39f55cc6186000ca89b',
    messagingSenderId: '367892405378',
    projectId: 'digital-campus-d2f80',
    storageBucket: 'digital-campus-d2f80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFliTburp4D15OIoTigvn6-LGDIlSGKpA',
    appId: '1:367892405378:ios:bdfc2dd4188ba7af0ca89b',
    messagingSenderId: '367892405378',
    projectId: 'digital-campus-d2f80',
    storageBucket: 'digital-campus-d2f80.firebasestorage.app',
    iosBundleId: 'com.example.digitalCampus',
  );

}