// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXjz5zIZnoadZO6c6FNQ-TPlO-D6s3Ems',
    appId: '1:253750054072:web:9528f32a723bf0e378384d',
    messagingSenderId: '253750054072',
    projectId: 'digital-campus-73003',
    authDomain: 'digital-campus-73003.firebaseapp.com',
    storageBucket: 'digital-campus-73003.firebasestorage.app',
    measurementId: 'G-HWELG3SHD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-eyRyLsKfBRgiwDc1uOAvzw8x5cZ-UMk',
    appId: '1:253750054072:android:b3ce516960bf3dd678384d',
    messagingSenderId: '253750054072',
    projectId: 'digital-campus-73003',
    storageBucket: 'digital-campus-73003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwNsTsOAKipGy6hc4fvP4jxcnh9emI0Gk',
    appId: '1:253750054072:ios:4766ee953bdb3e5978384d',
    messagingSenderId: '253750054072',
    projectId: 'digital-campus-73003',
    storageBucket: 'digital-campus-73003.firebasestorage.app',
    iosBundleId: 'com.example.digitalCampus',
  );

}